# Generated by Django 6.0 on 2026-03-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_order_special_request_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtheme',
            name='caste_preference',
            field=models.CharField(blank=True, help_text='For marriage events', max_length=100, null=True),
        ),
    ]
